### ISSUE TITLE
Migrate actual dispatcher to Zustand

### ISSUE THREAD

**Issue by RafaelGB** [RafaelGB/obsidian-db-folder#227]
As a second round of upgrades, the plugin has to update the actual strategy of modifications to something more scalable.

https://github.com/pmndrs/zustand

**Comment by RafaelGB** [comment]
After many adjustments, it seems that the basic architecture to make events work with Zustand works.
List of events to migrate:

- [ ] ADD_OPTION_TO_COLUMN
- [ ] ADD_ROW
- [ ] CHANGE_ROW_TEMPLATE:
- [ ] UPDATE_COLUMN_TYPE
- [ ] UPDATE_COLUMN_LABEL
- [ ] UPDATE_CELL
- [ ] UPDATE_OPTION_CELL
- [ ] ADD_COLUMN_TO_LEFT
- [ ] ADD_COLUMN_TO_RIGHT
- [ ] DELETE_COLUMN
- [ ] SETTINGS_COLUMN
- [ ] MODIFY_COLUMN_CONFIG
- [ ] SET_SORT_BY

**Comment by RafaelGB** [comment]
First steps... Correlation between cells!

https://user-images.githubusercontent.com/11924043/182404538-10b3361d-ae13-47d9-b260-ea0be00e9304.mov

**Comment by RafaelGB** [comment]
Finally all actions of the dispatcher were migrated
