### ISSUE TITLE
AND / OR  filter selector

### ISSUE THREAD

**Issue by javiavid** [RafaelGB/obsidian-db-folder#268]
It would be interesting to be able to select whether the filters are AND or OR with a button in the filter creation window.

**Comment by Subere** [comment]
Groups or different views would be awesome! So it would be possible to sqitch quickly between a table with all people from city_a to city_b. And easily activate and change filters,

Like in Notion.
![image](https://user-images.githubusercontent.com/67839301/187050401-4b2e6e31-7abe-4f71-8dcc-93efee74d681.png)

**Comment by RafaelGB** [comment]
@Subere sure, views has its own issue into the roadmap

**Comment by RafaelGB** [comment]
First steps to obtain AND/OR groups

<img width="1304" alt="Screenshot 2022-09-28 at 21 41 04" src="https://user-images.githubusercontent.com/11924043/192873970-3caa1f45-6c13-4567-93c5-c3e8c0d7d314.png">

**Comment by RafaelGB** [comment]
Task as requirements:
- [ ] Delete animate filters
- [ ] Edit condition for any lvl
- [ ] Edit field key for any lvl
- [ ] Edit operator for any lvl
- [ ] Edit value for any lvl
- [ ] Visually distinguish between filter levels
- [ ] Option to disable a filter without remove it
