### ISSUE TITLE
[FR] Mobile support

### ISSUE THREAD

**Issue by RafaelGB** [RafaelGB/obsidian-db-folder#27]
@bakerstreet reports that the application does not work on mobile property [here](https://forum.obsidian.md/t/database-based-on-folders/36204)

I am opening this issue

**Comment by RafaelGB** [comment]
progress report:
I refactored the edit function to be more consistent and scalable. Actually the edition of inline fields works. 
![Screen Recording 2022-05-06 at 17 21 44](https://user-images.githubusercontent.com/11924043/167163408-84502d3e-effa-4c56-abec-912f59f4daa3.gif)

roadmap:
- [x] Refactor edit to use dataview API
- [x] Edit inline fields
- [ ] Modify key when you edit label of column
- [ ] Remove field when you delete a column

**Comment by iamrecursion** [comment]
While it's not working is it possible to mark `isDesktopOnly` as true? That prevents it from trying and failing to load on every mobile start for the moment.

**Comment by RafaelGB** [comment]
oh that's right! I will change it. Thank you

**Comment by iamrecursion** [comment]
You may be able to debug this more effectively using [Obsidian REPL](https://github.com/ktemkin/obsidian-repl). Though it won't show the initial failure to load, it will pick up the error when you try and manually enable the plug-in.

**Comment by RafaelGB** [comment]
Nice plugin idea btw!
I will give it a try

**Comment by RafaelGB** [comment]
"isDesktopOnly": true added with 0.3.1

**Comment by iamrecursion** [comment]
Great! I look forward to proper mobile support!

**Comment by RafaelGB** [comment]
Nice! I am working with documentation with mkdocs

**Comment by RafaelGB** [comment]
Hi @iamrecursion do you need help with this issue?
Any progress? You can share with us so could be easy to help

**Comment by iamrecursion** [comment]
Oh, I think there's been some confusion! I didn't say that I could _work_ on it—unfortunately I've not got the time at the moment—just that I look forward to it being done! 

If this is still outstanding in a month or so I should be able to pick it up. 

I'm really sorry for the confusion!

**Comment by RafaelGB** [comment]
@iamrecursion oh do not sorry :) I will try to give mobile support with your debugging plugin

**Comment by RafaelGB** [comment]
Trying to debug on mobile while is load with this templater script but does not load on mobile yet:

```js
// Call this method inside your plugin's
// `onload` function like so:
// monkeyPatchConsole(this);
function monkeyPatchConsole(path){
    console.log("=> monkeyPatchConsole");
    // if (!Platform.isMobile) {
    //     return;
    // }

    const logFile = `${path}/${new Date().toLocaleDateString('sv')}.log`;
    const logs = [];
    const logMessages = (prefix) => (messages) => {
        logs.push(`\n[${prefix}]`);
        for (const message of messages) {
            logs.push(String(message));
        }
        window.app.vault.adapter.write(logFile, logs.join(" "));
    };

    console.debug = logMessages("debug");
    console.error = logMessages("error");
    console.info = logMessages("info");
    console.log = logMessages("log");
    console.warn = logMessages("warn");
    console.log(`<= monkeyPatchConsole ${logFile}`);
}

module.exports = monkeyPatchConsole;
```

**Comment by RafaelGB** [comment]
I generate a mini plugin just to debug on mobile.

[mobile-debug.zip](https://github.com/RafaelGB/obsidian-db-folder/files/9541523/mobile-debug.zip)

Once I found the problem (`[error] Plugin failure: dbfolder ReferenceError: Can't find variable: process`) I used the plugin of rollup `@rollup/plugin-replace` to substitute in exec time the variable `process` for a controlled one

```js
const getRollupPlugins = (tsconfig, ...plugins) =>
    [
        typescript2(tsconfig),
        nodeResolve({ browser: true }),
        json(),
        commonjs(),
        replace({
            'process.env.NODE_ENV': JSON.stringify(isProd ? 'production' : 'development')
        })
    ].concat(plugins);

```

aaaand... Its working! I am sure there are tons of bugs just for mobile but at least the table is loading correctly

**Comment by iamrecursion** [comment]
That's very exciting!
