### ISSUE TITLE
[FR] - Edit nested metadata

### ISSUE THREAD

**Issue by RafaelGB** [RafaelGB/obsidian-db-folder#442]
I've tried the version that implemented this issue and I can't understand what was really done.

The 2.6.7 release section says "Frontmatter editions now respect nested metadata". This means that nested metadata **won't be messed up** by the plugin or nested metadata will be **supported** by the plugin?

Because I thought the @kvietcong possible solution was accepted and implemented, where:
```yaml
level1:
  level2:
```
would be considered as `level1.level2` as the name field by the plugin.

When I create a field separating field levels by dot, the DB turns empty (error). ![image](https://user-images.githubusercontent.com/18124316/192816566-e19fb404-8614-48fc-b4c1-486abf182af8.png)

When I try to create a field that already exists in DB ![image](https://user-images.githubusercontent.com/18124316/192818378-1b490373-4d65-4dc1-aa85-57e819e5ab48.png), only the `level1` can be added ![image](https://user-images.githubusercontent.com/18124316/192818521-17f2a809-0ff5-4696-bfc7-01543125f1fe.png)
and the data is shown as json in DB: ![image](https://user-images.githubusercontent.com/18124316/192818819-0c440c98-12f7-43cd-bf7d-97d748e60eca.png).
If this data is edited by plugin, the nested metadata in YAML will be messed up:
![image](https://user-images.githubusercontent.com/18124316/192819086-7499eeef-e49e-4a6f-a3e6-a1beeb768cb1.png).

Is there another issue related to what I've described above?

_Originally posted by @www-wagner in https://github.com/RafaelGB/obsidian-db-folder/issues/194#issuecomment-1261082733_

**Comment by dalewking** [comment]
I too thought we were getting this as part of #194

**Comment by RafaelGB** [comment]
Support the edition could be much more complex. With https://github.com/RafaelGB/obsidian-db-folder/issues/194 atleast we do not break your yamls

**Comment by RafaelGB** [comment]
First steps to allow objects on text column, stringinfy and parsing with JSON function.

https://user-images.githubusercontent.com/11924043/193642321-4937d161-0de2-4849-bf73-727fac573c75.mov

Advantages:
- Edition of an object in any level of the tree
- improvement to formulas. Now you can access all your nested metadata inside the formula function (I.E.: `${row.first.nestedSecond.third[0]}` will return `1` in our video example)

The idea will be just render the deserved using a new config column. `indicate your nested metadata: "first.second.third"` to configure some tags for example `[1,2,3]` and adding `4`. Then the entire object will be saved with the changes

**Comment by www-wagner** [comment]
Are you planning to separate tree items in different fields in the UI table?

In your example, the table would contain the following columns:
- `first.second`: `Text` type
- `first.nestedSecond.third`: `List` type
- `first.nestedSecond.anotherNested.testing1`: `Text` type
and so on...

I guess the UI would be much more user friendly.

Or this would be so complex?

**Comment by RafaelGB** [comment]
as we said, you can use formulas for it. So if you want multiple fields of the same tree you can create different formulas calling row.first.(whatever you want)

**Comment by RafaelGB** [comment]
A column cant contain dots so your  label has to be another one. The property will be another

**Comment by RafaelGB** [comment]
There are two new configurations (currently just for text). The first will enable the nested behaviour. The second one will modify the actual id of your column for a nested one separated by commas.

Read and write its working correctly! The next step will be allow multiple fields of the same nested column. I am keeping working on it. It will takes time.

Problems to resolve
- [ ] modify label of the column that only affects the nested one
- [ ] allow multiple fields for the same column
- [ ] enable the nested behaviour for the rest of the types

https://user-images.githubusercontent.com/11924043/194858306-340ddfd1-919a-46bf-a778-1d1d38a0bc50.mov

**Comment by RafaelGB** [comment]
due to the release of version 1.0.0 of Obsidian I am going to release a new minor version with everything developed at the moment and I will keep track of the improvements in another branch

pending issues:

- [ ] re render animated values correctly once a parent one is edited
- [ ] Better control of edit the parent key for multiple values if one is changed
