### ISSUE TITLE
[FR]: Design overhaul

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#577]
### Contact Details

imed#8086

## Intro
This is kind of a big issue, regrouping everything about the plugin design, to avoid further visual issues about supporting other **themes** and to also avoid **mobile** visual problems.

I have no experience in CSS, but when I compare this plugin to the **kanban** plugin or the **projects** plugin, I notice that this plugin uses non-native obsidian elements (or whatever they're called) which cause these types of problems. Here are some examples :
- the filter button and the search bar can't be used on mobile ;
- the column menu to change the property type cannot be displayed on small screens ;
- the row height changes from theme to theme, even when setting it to normal in the database settings.

## Design proposal
With a mix of the two plugins mentioned above, here is the new design proposition :

![db folder mockup](https://user-images.githubusercontent.com/38974541/199736694-3ccfcb87-8810-4741-a476-f09f4a83c4a4.jpg)

### The database's top bar
- The `add button` is removed and placed in the page header like the kanban plugin, and when pressed a modal would appear, making it easy to use on mobile devices. The use of templates will be migrated to the database settings like this :
    - use templates (yes/no) ;
    - choose the template with a file picker.
- The `open markdown`, `import`, `export`, `open db settings`, and `manage filter` will also be placed either in the page header or the obsidian menu. And don't worry, regarding this issue https://github.com/RafaelGB/obsidian-db-folder/issues/359#issuecomment-1253359668 you can keep the header bar enabled, even if the user hides it in the setting, that's how the kanban plugin does it ;
- The `enable filter button` will be removed and set to always enable filters, and if needed we could add a refresh button to the page header ;
- The `search` will behave just like the kanban plugin ;
- The `filter groups named buttons` will have the same style as the projects plugin tabs
- The `pagination` can be put in as the last row

The main objective behind these changes is to remove as much as possible from the database's top bar to enable mobile support

### The column menu
it will be replaced with a custom obsidian menu that can be toggled with either a right click and/or with a custom column button. The menu will have these options :
- property type which will create an obsidian modal (works with mobile)
- sort ascending
- sort descending
- remove sort
- insert left
- insert right
- hide
- delete
- column settings

## Recap 
My solution may be radical, but in the long term, I think it'll be worth it because of these benefits :
- Support for the mobile app without much work ;
- Support for most themes without much work ;
- The plugin will feel much more native to obsidian ;
- Seamless integration with the projects plugin in terms of design.

I know this is a big change, but you don't have to migrate all elements immediately. I'd say the priority is the top bar. Then maybe in the future, I'll open another issue for migrating the table/column to the new design.

If you agree to this proposition and would be willing to receive help, I could send a message to the `theme-dev` channel in discord, maybe a theme developer would offer to help out with the redesign. This is because DB folder is popular and this will help them in turn not get any unwanted issues in their theme repository.

### For which platform do you request this request??

Cross

**Comment by RafaelGB** [comment]
- [ ] Force to show tab title bar
- [ ] Move menu actions to bar
- [ ] Move filter actions to bar
- [ ] Search button/input on bar
- [ ] new keyboard action to focus on global search

Move Pagination to bar? to bottom? We will see

**Comment by imeed166** [comment]
> Move Pagination to bottom?

Maybe something like this 

![image](https://user-images.githubusercontent.com/38974541/203749416-68b7d5f7-c648-446e-9d8f-ece4d44fe618.png)


or this 
![image](https://user-images.githubusercontent.com/38974541/203749470-23cddd79-8c8b-4ae3-affe-38214feaf593.png)
![image](https://user-images.githubusercontent.com/38974541/203749548-f911abc7-c1cf-4012-88b8-92c7c6d1a974.png)

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/204010857-d8abbb63-8e55-46a0-a166-6a380f9f994d.mov

ctrl+F keyboard shortcut working
